name = "Universal"
license = "MIT"
licenselink = "https://github.com/devcows/hugo-universal-theme/blob/master/LICENSE"
description = "A port of the Universal theme"
homepage = "//github.com/devcows/hugo-universal-theme"
tags = ["blog", "articoli", "recensioni", "progetti", "minimal", "responsive"]
features = ["blog", "tech", "disqus", "minimal", "responsive"]
min_version = 0.15

[author]
    name = "Stefano Valentini"
    homepage = "//stefanovalentini.life"

# If Porting existing theme
[original]
    author =  "bootstrapious"
    homepage = "http://bootstrapious.com/p/universal-business-e-commerce-template"
